export default {
  BASE_DARK: '#00283b',
  ORANGE: '#FF5B5E',
  FONT_SIZE_EXTRA_SMALL: 9,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_MEDIUM_SMALL: 16,
  FONT_SIZE_MEDIUM__REGULAR: 22,
  FONT_SIZE_LARGE: 30,
  FONT_SIZE_EXTRA_LARGE: 36,
};